repos:
  - repo: local
    hooks:
      - id: matlab-mbeautifier
        name: MATLAB MBeautifier Pre-Commit
        entry: bash scripts/precommit_format.sh
        language: system
        pass_filenames: false
